feat: introduce script to automate simple changes to components
AlaskaAirlines/auro-library pull request #17
Opened 2023-07-08 03:35 UTC by Izook

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** # (issue, if applicable)

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [ ] My update follows the CONTRIBUTING guidelines of this project
- [ ] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2023-07-10 19:07 UTC, blackfalcon requested changes

2023-07-10 19:07 UTC, blackfalcon commented on scripts/config/propogateAuroChange.sh
> +#   - AlaskaAirlines GitHub PAT
This PAT. Is this unique for each user and only used in the CLI or does this have to be registered with every repo?

2023-07-10 19:07 UTC, blackfalcon commented on scripts/config/propogateAuroChange.sh
> +#!/bin/bash
This document is a template, not actually useable in its current state? If that is the case, we should be more declarative about that.

2023-07-10 19:07 UTC, blackfalcon commented on scripts/config/propogateAuroChange.sh
> +rm -rf ./workspace
This feels like brute force. What if the repo is already using a `./workspace` dir?

2023-07-10 19:08 UTC, blackfalcon commented
There is no issue linking this work back to the Kanban. Temporarily assigned the PR to the project.

2023-07-18 22:38 UTC, Izook commented on scripts/config/propogateAuroChange.sh
> +repos=$(gh repo list $repoOwner \
We should update this filter to use an allow/block repo list that would empower us to apply this change to select repos or ignore certain repos.

2024-02-12 17:02 UTC, blackfalcon commented
Closing this pull request and moving the issue to a Discussion for the team to review and discuss.

2024-02-12 17:02 UTC, closed without merging